name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  actions: read

jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
